<?php

/**
 * @file
 * The Zend module for Drupal ensures that the Zend Framework is installed.
 */

/**
 * Implementation of hook_init().
 */
function zend_init() {
  // Due to the dependance on the libraries module being included, we wait until
  // hook_init() to register the Zend Loader.
  if ($path = zend_get_path()) {
    require_once $path .'/Loader/Autoloader.php';
    Zend_Loader_Autoloader::getInstance();
  }
}

/**
 * Retrieve the expected path to the Zend Framework.
 *
 * @return
 *   The path where the Zend Framework is to be expected to be installed.
 */
function zend_get_path() {
  // A path can be configured to the location of the library.
  $path = variable_get('zend_path', FALSE);

  if (!$path) {
    // Check if the libraries module is installed and if the Zend Framework is
    // being supplied through the libraries module.
    if (module_exists('libraries')) {
      $libraries = libraries_get_libraries();
      if (isset($libraries['Zend'])) {
        $path = libraries_get_path('Zend');
      }
    }

    // Check if the Zend Framework is in the include path.
    if (!$path) {
      $include_paths = explode(PATH_SEPARATOR, get_include_path());
        foreach ($include_paths as $include_path) {
          if (is_dir($include_path .'/Zend')) {
            $path = $include_path .'/Zend';
            break;
          }
        }
    }
  }

  return $path;
}
